### ISSUE TITLE
any plan to support application/did+json ?

### ISSUE THREAD

**Issue by OR13** [trinsic-id/did-key.rs#3]
We are trying to get did key to easily support JWK and Base58 by using the content type and representation specific resolutions, see https://github.com/transmute-industries/did-key.js/blob/master/packages/test-vectors/src/did-core-conformance/bls12381_g1andg2/bls12381_g1andg2.json

any interest on your side for supporting `application/did+json` ?

**Comment by tmarkovski** [comment]
Yeah, it would be pretty trivial to support this.

**Comment by tmarkovski** [comment]
To confirm, the JWK values for `x` and `d` are base64url encoded with *no* padding?

**Comment by OR13** [comment]
yep, but always better to write tests to confirm, with a popular library / window.crypto :)
